# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shared-cpm-tests-dask-gateway
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Gi
  csi:
    driver: nfs.manila.csi.openstack.org
    volumeHandle: 2d877e2f-5ff4-4ed8-8141-ba13a59d0aa6
    volumeAttributes:
      cephfs-mounter: fuse
      shareAccessIDs: d87fb4c6-9d49-4216-96af-284c860284bc
      shareID: 2d877e2f-5ff4-4ed8-8141-ba13a59d0aa6
      storage.kubernetes.io/csiProvisionerIdentity: 1789626076806-330-nfs.manila.csi.openstack.org
    nodePublishSecretRef:
      name: csi-manila-secrets
      namespace: default
    nodeStageSecretRef:
      name: csi-manila-secrets
      namespace: default
    controllerExpandSecretRef:
      name: csi-manila-secrets
      namespace: default
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-manila-nfs
  volumeMode: Filesystem
  claimRef:
    name: shared-cpm-tests
    namespace: dask-gateway
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-cpm-tests
  namespace: dask-gateway
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: csi-manila-nfs
  volumeName: pv-shared-cpm-tests-dask-gateway
