# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Build the base dask-gateway image for local mode.
# Target Docker image name:
# ghcr.io/rs-python/dask/dask-gateway:local-py<PYTHON_VERSION_BASE>-<DASK_TAG>
#

ARG PYTHON_VERSION_BASE=xxx
FROM python:${PYTHON_VERSION_BASE}-slim-bookworm

ARG DASK_TAG=xxx
ARG DASK_GATEWAY_TAG=xxx

COPY ./layer-cleanup.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh

COPY ./dask-gateway /opt/dask-gateway
COPY ./dask-gateway-server /opt/dask-gateway-server

# Do the same as in:
# https://github.com/dask/dask-gateway/blob/main/dask-gateway/Dockerfile
# https://github.com/dask/dask-gateway/blob/main/dask-gateway-server/Dockerfile

# Install tini and upgrade linux packages are updated to patch known
# vulnerabilities.
RUN apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y \
        tini \
 && layer-cleanup.sh

# Install the requirements.txt files and our custom dependencies.
# Add bokeh and jupyter-server-proxy for the dask dashboard.
RUN \
    pip install --upgrade pip && \
    pip install -r /opt/dask-gateway/Dockerfile.requirements.txt && \
    pip install -r /opt/dask-gateway-server/Dockerfile.requirements.txt && \
    pip install \
        dask==${DASK_TAG} \
        distributed==${DASK_TAG} \
        dask-gateway==${DASK_GATEWAY_TAG} \
        dask-gateway-server[local,kubernetes]==${DASK_GATEWAY_TAG} \
        bokeh">=3.1.0" \
        jupyter-server-proxy \
    && layer-cleanup.sh

# Remove custom scripts
RUN rm -rf /usr/local/bin/layer-cleanup.sh /opt/dask-gateway /opt/dask-gateway-server

# Create a non-root user to run as
RUN useradd --create-home --user-group --uid 1000 dask
USER dask:dask
ENV PATH=/home/dask/.local/bin:$PATH
WORKDIR /home/dask/

ENTRYPOINT ["tini", "-g", "--"]
CMD ["dask-gateway-server"]

# Set labels based on the Open Containers Initiative (OCI):
# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
#
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-workflow-env"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-workflow-env/blob/develop/docker/base/Dockerfile.dask"
