#!/usr/bin/env bash
# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Target Docker image names:
# ghcr.io/rs-python/quay.io/jupyter/base-notebook:hub-xxx
#

# shellcheck disable=SC2102

# quay.io/jupyter/base-notebook:hub-<tag>-py<python_version>
ARG BASE=xxx
FROM "${BASE}"
ARG BASE=xxx

ENV PATH="/home/jovyan/.local/bin:${PATH}"

ARG PYTHON_VERSION=3.13.12
ARG DASK_TAG=2024.5.2
ARG DASK_TAG_STAGING=2026.1.2
ARG DASK_GATEWAY_TAG=2025.4.0
ARG PREFECT_TAG=3.6.20

USER root

COPY ./layer-cleanup.sh ./restore-apt.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh
RUN apt update && apt upgrade -y && layer-cleanup.sh

# Install python version and dependencies
RUN python -V && \
    pip install \
        dask[complete]=="${DASK_TAG}" \
        distributed=="${DASK_TAG}" \
        dask-gateway=="${DASK_GATEWAY_TAG}" \
        prefect[aws]=="${PREFECT_TAG}" \
        ipywidgets \
        s3fs \
        boto3 && \
    layer-cleanup.sh

# Install packages
RUN restore-apt.sh && apt update && apt install -y python3-pydot graphviz && layer-cleanup.sh

# Install specific Python environment for staging (needs Dask v.2026.1.2)
RUN python -m venv /opt/venv/dask-staging && \
    source /opt/venv/dask-staging/bin/activate && \
    pip install -U pip && \
    pip install \
        dask[complete]=="${DASK_TAG_STAGING}" \
        distributed=="${DASK_TAG_STAGING}" \
        dask-gateway=="${DASK_GATEWAY_TAG}"

RUN chown -R jovyan /home/jovyan
RUN rm -f /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

USER jovyan

# Set labels based on the Open Containers Initiative (OCI):
# https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
#
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-workflow-env"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-workflow-env/blob/develop/docker/base/Dockerfile.jupyter"
