# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

## Common parameters
# -- fully override common.names.fullname
fullnameOverride: "{{ prefect3worker.eopf.name }}"

worker:
  clusterUid: "rspy"
  image:
    repository: prefecthq/prefect
    prefectTag: 3.2.13-python3.11-kubernetes
    pullPolicy: IfNotPresent
  apiConfig: selfHostedServer
  config:
    workPool: {{ prefect3worker.eopf.name }}
    limit: 200
    baseJobTemplate:
      name: {{ prefect3worker.eopf.name }}-base-job-template
      configuration: |
        {
          "variables": {
            "type": "object",
            "properties": {
              "env": {
                "type": "object",
                "title": "Environment Variables",
                "description": "Environment variables to set when starting a flow run.",
                "additionalProperties": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ]
                }
              },
              "name": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "{{ prefect3worker.eopf.name }}",
                "description": "Name given to infrastructure created by a worker."
              },
              "image": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Image",
                "examples": [
                  "docker.io/prefecthq/prefect:3.2.13-python3.11-kubernetes"
                ],
                "description": "The image reference of a container image to use for created jobs. If not set, the latest Prefect image will be used."
              },
              "labels": {
                "type": "object",
                "title": "Labels",
                "description": "Labels applied to infrastructure created by a worker.",
                "additionalProperties": {
                  "type": "string"
                }
              },
              "command": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Command",
                "description": "The command to use when starting a flow run. In most cases, this should be left blank and the command will be automatically generated by the worker."
              },
              "namespace": {
                "type": "string",
                "title": "Namespace",
                "default": "processing",
                "description": "The Kubernetes namespace to create jobs within."
              },
              "stream_output": {
                "type": "boolean",
                "title": "Stream Output",
                "default": true,
                "description": "If set, output will be streamed from the job to local standard output."
              },
              "cluster_config": {
                "anyOf": [
                  {
                    "$ref": "#/definitions/KubernetesClusterConfig"
                  },
                  {
                    "type": "null"
                  }
                ],
                "description": "The Kubernetes cluster config to use for job creation."
              },
              "finished_job_ttl": {
                "anyOf": [
                  {
                    "type": "integer"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Finished Job TTL",
                "default": 86400,
                "description": "The number of seconds to retain jobs after completion. If set, finished jobs will be cleaned up by Kubernetes after the given delay. If not set, jobs will be retained indefinitely."
              },
              "image_pull_policy": {
                "enum": [
                  "IfNotPresent",
                  "Always",
                  "Never"
                ],
                "type": "string",
                "title": "Image Pull Policy",
                "default": "IfNotPresent",
                "description": "The Kubernetes image pull policy to use for job containers."
              },
              "service_account_name": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Service Account Name",
                "description": "The Kubernetes service account to use for job creation."
              },
              "job_watch_timeout_seconds": {
                "anyOf": [
                  {
                    "type": "integer"
                  },
                  {
                    "type": "null"
                  }
                ],
                "title": "Job Watch Timeout Seconds",
                "description": "Number of seconds to wait for each event emitted by a job before timing out. If not set, the worker will wait for each event indefinitely."
              },
              "pod_watch_timeout_seconds": {
                "type": "integer",
                "title": "Pod Watch Timeout Seconds",
                "default": 60,
                "description": "Number of seconds to watch for pod creation before timing out."
              }
            },
            "definitions": {
              "KubernetesClusterConfig": {
                "type": "object",
                "title": "KubernetesClusterConfig",
                "required": [
                  "config",
                  "context_name"
                ],
                "properties": {
                  "config": {
                    "type": "object",
                    "title": "Config",
                    "description": "The entire contents of a kubectl config file."
                  },
                  "context_name": {
                    "type": "string",
                    "title": "Context Name",
                    "description": "The name of the kubectl context to use."
                  }
                },
                "description": "Stores configuration for interaction with Kubernetes clusters.\n\nSee `from_file` for creation.",
                "secret_fields": [],
                "block_type_slug": "kubernetes-cluster-config",
                "block_schema_references": {}
              }
            },
            "description": "Default variables for the Kubernetes worker.\n\nThe schema for this class is used to populate the `variables` section of the default\nbase job template."
          },
          "job_configuration": {
            "env": "{% raw %}{{ env }}{% endraw %}",
            "name": "{{ prefect3worker.eopf.name }}-job-",
            "labels": "{% raw %}{{ labels }}{% endraw %}",
            "command": "{% raw %}{{ command }}{% endraw %}",
            "namespace": "processing",
            "job_manifest": {
              "kind": "Job",
              "spec": {
                "template": {
                  "spec": {
                    "affinity": {
                      "nodeAffinity": {
                        "requiredDuringSchedulingIgnoredDuringExecution": {
                          "nodeSelectorTerms": [
                            {
                              "matchExpressions": [
                                {
                                  "key": "node-role.kubernetes.io/prefect_flow",
                                  "operator": "Exists"
                                }
                              ]
                            }
                          ]
                        }
                      }
                    },
                    "tolerations": [
                      {
                          "effect": "NoSchedule",
                          "key": "role",
                          "operator": "Equal",
                          "value": "prefect_flow"
                      }
                    ],
                    "containers": [
                      {
                        "env": "{% raw %}{{ env }}{% endraw %}",
                        "args": "{% raw %}{{ command }}{% endraw %}",
                        "name": "prefect-job",
                        "image": "ghcr.io/rs-python/prefect/rs-client-libraries/k8s:latest",
                        "imagePullPolicy": "IfNotPresent",
                        "resources":{
                          "requests": {
                            "cpu": "150m",
                            "memory": "256Mi"
                            },
                          "limits": {
                            "cpu": "300m",
                            "memory": "512Mi"
                          }
                        }
                      }
                    ],
                    "completions": 1,
                    "parallelism": 1,
                    "restartPolicy": "Never",
                    "serviceAccountName": "{{ prefect3worker.eopf.name }}"
                  }
                },
                "backoffLimit": 0,
                "ttlSecondsAfterFinished": 86400
              },
              "metadata": {
                "labels": "{% raw %}{{ labels }}{% endraw %}",
                "namespace": "processing",
                "generateName": "{{ prefect3worker.eopf.name }}-run-"
              },
              "apiVersion": "batch/v1"
            },
            "stream_output": "{% raw %}{{ stream_output }}{% endraw %}",
            "cluster_config": "{% raw %}{{ cluster_config }}{% endraw %}",
            "job_watch_timeout_seconds": "{% raw %}{{ job_watch_timeout_seconds }}{% endraw %}",
            "pod_watch_timeout_seconds": "{% raw %}{{ pod_watch_timeout_seconds }}{% endraw %}"
          }
        }

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/processing"
              operator: Exists
  tolerations:
    - key: role
      operator: Equal
      value: processing
      effect: NoSchedule

  selfHostedServerApiConfig:
    apiUrl: http://prefect-server.processing.svc.cluster.local:4200/api

  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
  livenessProbe:
    enabled: true

  replicaCount: {{ prefect3worker.eopf.number | default(2) }}
