# Copyright 2025 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This Dockerfiles installs a DPR processor in the dask-gateway image for local and cluster modes.

ARG PYTHON_VERSION_DPR=3.11.7
ARG DASK_GATEWAY_TAG=2024.1.0

FROM ghcr.io/rs-python/dask/dask-gateway:${DASK_GATEWAY_TAG}-py${PYTHON_VERSION_DPR}

ARG IMAGE2BUILD

# Default user from parent image
ARG USER=dask:dask

# Do everything from root
USER root

COPY ./resources/layer-cleanup.sh ./resources/restore-apt.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

# System installations
RUN \
    restore-apt.sh && apt update && \
    apt install -y git && \
    layer-cleanup.sh

# Install processor and eopf
ADD ./resources/requirements-*.txt /opt
# NOTE, with older docker versions, use:
# RUN --mount=type=secret,id=GITLAB_EOPF_TOKEN \
# GITLAB_EOPF_TOKEN=$(cat /run/secrets/GITLAB_EOPF_TOKEN) pip install ...
RUN --mount=type=secret,id=GITLAB_EOPF_TOKEN,env=GITLAB_EOPF_TOKEN \
    pip install -U pip && \
    pip install -U -r /opt/requirements-${IMAGE2BUILD}.txt && \
    layer-cleanup.sh

# Install complete dask subsets
RUN pip install dask[complete] && layer-cleanup.sh

# Other installations
RUN restore-apt.sh && apt update && apt install -y python3-pydot graphviz && layer-cleanup.sh

# Install and auto configure opentelemetry
RUN pip install opentelemetry-distro opentelemetry-exporter-otlp opentelemetry-instrumentation-aws-lambda opentelemetry-test-utils && \
    opentelemetry-bootstrap -a install && \
    layer-cleanup.sh

# Run post-install script if it exists
ADD ./resources/post-install-*.sh /opt
RUN \
    if [ -f /opt/post-install-${IMAGE2BUILD}.sh ]; then \
        /opt/post-install-${IMAGE2BUILD}.sh && \
        layer-cleanup.sh; \
    fi \
    rm -f /opt/post-install-*.sh

# Clean everything
RUN apt autoremove -y git
RUN rm -rf /opt/requirements-*.txt /opt/post-install-*.sh

# Remove custom scripts
RUN rm -f /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

# Restore user
USER $USER

# Set labels based on the Open Containers Initiative (OCI):
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-demo"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-demo/blob/develop/local-mode/docker/Dockerfile.dask-eopf-local"

# This Dockerfile is used to build:
# ghcr.io/rs-python/dask/l0
# ghcr.io/rs-python/dask/s1ard
