# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# This Dockerfile installs the mock DPR processor in the dask-gateway image for local and cluster modes.
# Target Docker image name:
# ghcr.io/rs-python/dask/mockup
#

# Base image type: can be "k8s" for cluster usage or "local" for local usage.
ARG BASE_IMAGE_TARGET=xxx

ARG PYTHON_VERSION_DPR=3.11.7
ARG DASK_TAG=2024.5.2

# Get the contents from the rs-testmeans_dpr-processor-mock image
FROM ghcr.io/rs-python/rs-testmeans_dpr-processor-mock:latest AS dpr_mock

FROM ghcr.io/rs-python/dask/dask-gateway:${BASE_IMAGE_TARGET}-py${PYTHON_VERSION_DPR}-${DASK_TAG}

# Default user from parent image
ARG USER=dask:dask
ARG USER_NAME=dask

USER root
COPY --from=docker-scripts ./layer-cleanup.sh ./restore-apt.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

############################################
# Install the DPR mockup (=fake processor) #
############################################

# Copy the src folder from the dpr_mock image
COPY --from=dpr_mock /src /src
WORKDIR /src/DPR

# Give USERNAME rights to write in /src
RUN chown -R $USER_NAME /src

# Export the poetry dependencies into a requirements.txt file then install it with pip
RUN \
    pip install -U pip && \
    pip install --no-cache-dir poetry pip-autoremove && \
    poetry self add poetry-plugin-export && \
    poetry export --without-hashes --format=requirements.txt > requirements.txt && \
    pip-autoremove -y poetry && \
    pip install -r requirements.txt && \
    rm -f requirements.txt && \
    layer-cleanup.sh

##################
# End DPR mockup #
##################

# Install complete dask subsets
RUN pip install dask[complete] && layer-cleanup.sh

# Other installations
RUN \
    restore-apt.sh && apt update && \
    apt install -y python3-pydot graphviz && \
    layer-cleanup.sh

# Install and auto configure opentelemetry
RUN pip install opentelemetry-distro opentelemetry-exporter-otlp && \
    opentelemetry-bootstrap -a install && \
    layer-cleanup.sh

# Remove custom scripts
RUN rm -f /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

USER $USER

# Set labels based on the Open Containers Initiative (OCI):
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-demo"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-demo/blob/develop/local-mode/docker/eopf/Dockerfile.dask-eopf-mockup-local"
