# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This Dockerfiles installs a DPR processor in the rs-dpr-service image,
# to be able to run the processor with the Dask LocalCluster mode in local mode.

#
# Target Docker image name:
# ghcr.io/rs-python/dask/l0/localcluster
# ghcr.io/rs-python/dask/s1ard/localcluster
#

ARG PYTHON_VERSION=xxx
ARG DASK_TAG=xxx

FROM ghcr.io/rs-python/rs-dpr-service_py${PYTHON_VERSION}-${DASK_TAG}:latest

ARG IMAGE2BUILD

# Default user from parent image
ARG USER=user

# Do everything from root
USER root

COPY --from=docker-scripts ./layer-cleanup.sh ./restore-apt.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

# System installations
RUN \
    restore-apt.sh && apt update && \
    apt install -y git curl && \
    layer-cleanup.sh

# Install processor and eopf
ADD ./resources/requirements-*.txt /opt
# NOTE, with older docker versions, use:
# RUN --mount=type=secret,id=GITLAB_EOPF_TOKEN \
# GITLAB_EOPF_TOKEN=$(cat /run/secrets/GITLAB_EOPF_TOKEN) pip install ...
RUN --mount=type=secret,id=GITLAB_EOPF_TOKEN,env=GITLAB_EOPF_TOKEN \
    git config --global url."https://__token__:${GITLAB_EOPF_TOKEN}@gitlab.eopf.copernicus.eu/".insteadOf "https://gitlab.eopf.copernicus.eu/" && \
    pip install --only-binary=:all: -U pip && \
    pip install --prefer-binary -U -r /opt/requirements-${IMAGE2BUILD}.txt && \
    layer-cleanup.sh && \
    rm -rf /opt/requirements-*.txt

# Install complete dask subsets

RUN pip install --only-binary=:all: dask[complete] && layer-cleanup.sh

# Other installations
RUN \
    restore-apt.sh && \
    apt update && \
    apt install -y \
        python3-pydot graphviz && \
    pip install --only-binary=:all: \
        bokeh">=3.1.0" \
        jupyter-server-proxy && \
    layer-cleanup.sh

# Install and auto configure opentelemetry

RUN pip install --only-binary=:all: opentelemetry-distro opentelemetry-exporter-otlp "opentelemetry-instrumentation-eopf>=0.2.8" && \
    opentelemetry-bootstrap -a install && \
    layer-cleanup.sh

# Env var to the folder where we store the config files for the payload files.
ENV PAYLOAD_CONFIG_FILES=/opt/${IMAGE2BUILD}
RUN mkdir -p "$PAYLOAD_CONFIG_FILES"

# Run post-install script if it exists
ADD ./resources /opt/resources
RUN \
    if [ -f /opt/resources/post-install-${IMAGE2BUILD}.sh ]; then \
        /opt/resources/post-install-${IMAGE2BUILD}.sh && \
        layer-cleanup.sh; \
    fi && \
    rm -rf /opt/resources

# Clean everything
RUN apt autoremove -y git curl && layer-cleanup.sh

# Remove custom scripts
RUN rm -f /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

# Restore user
USER $USER

# Set labels based on the Open Containers Initiative (OCI):
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-workflow-env"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-workflow-env/blob/develop/docker/eopf/Dockerfile.dask-eopf-localcluster"
