# Copyright 2025 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This Dockerfiles installs a DPR processor in the dask-gateway image for local and cluster modes.

#
# Target Docker image name:
# ghcr.io/rs-python/dask/l0
# ghcr.io/rs-python/dask/s1ard
#

# Base image type: can be "k8s" for cluster usage or "local" for local usage.
ARG BASE_IMAGE_TARGET=xxx

# Versions used: currently all processors use Dask 2024.5.2 with Python 3.11.7, and the base images are all built with dask-gateway 2025.4.0
# Base images for local mode also include dask-gateway-server with the same version as dask-gateway
# ANY VERSION CHANGE MUST BE UPDATED IN THE BASE IMAGES SCRIPT GENERATOR (docker/base/build-base-images.sh) AND IN THIS FILE.
ARG PYTHON_VERSION_DPR=3.11.7
ARG DASK_TAG=2024.5.2

FROM ghcr.io/rs-python/dask/dask-gateway:${BASE_IMAGE_TARGET}-py${PYTHON_VERSION_DPR}-${DASK_TAG}

ARG IMAGE2BUILD

# Default user from parent image
ARG USER=dask:dask

# Do everything from root
USER root

COPY --from=docker-scripts ./layer-cleanup.sh ./restore-apt.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

# System installations
RUN \
    restore-apt.sh && apt update && \
    apt install -y git && \
    layer-cleanup.sh

# Install processor and eopf
ADD ./resources/requirements-*.txt /opt
# NOTE, with older docker versions, use:
# RUN --mount=type=secret,id=GITLAB_EOPF_TOKEN \
# GITLAB_EOPF_TOKEN=$(cat /run/secrets/GITLAB_EOPF_TOKEN) pip install ...
RUN --mount=type=secret,id=GITLAB_EOPF_TOKEN,env=GITLAB_EOPF_TOKEN \
    pip install -U pip && \
    pip install -U -r /opt/requirements-${IMAGE2BUILD}.txt && \
    layer-cleanup.sh && \
    rm -rf /opt/requirements-*.txt

# Install complete dask subsets
RUN pip install dask[complete] && layer-cleanup.sh

# Other installations
RUN restore-apt.sh && apt update && apt install -y python3-pydot graphviz && layer-cleanup.sh

# Install and auto configure opentelemetry
RUN pip install opentelemetry-distro opentelemetry-exporter-otlp opentelemetry-instrumentation-aws-lambda opentelemetry-test-utils && \
    opentelemetry-bootstrap -a install && \
    layer-cleanup.sh

# Env var to the folder where we store the config files for the payload files.
ENV PAYLOAD_CONFIG_FILES=/opt/${IMAGE2BUILD}
RUN mkdir -p "$PAYLOAD_CONFIG_FILES"

# Run post-install script if it exists
ADD ./resources /opt/resources
RUN \
    if [ -f /opt/resources/post-install-${IMAGE2BUILD}.sh ]; then \
        /opt/resources/post-install-${IMAGE2BUILD}.sh && \
        layer-cleanup.sh; \
    fi && \
    rm -rf /opt/resources

# Clean everything
RUN apt autoremove -y git && layer-cleanup.sh

# Remove custom scripts
RUN rm -f /usr/local/bin/layer-cleanup.sh /usr/local/bin/restore-apt.sh

# Restore user
USER $USER

# Set labels based on the Open Containers Initiative (OCI):
LABEL org.opencontainers.image.source="https://github.com/RS-PYTHON/rs-workflow-env"
LABEL dockerfile.url="https://github.com/RS-PYTHON/rs-workflow-env/blob/develop/local-mode/docker/eopf/Dockerfile.dask-eopf"
