# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -- Namespace for the deployment
namespace: operational

# -- Number of replicas for the deployment
replicaCount: 1

app:
  # -- Port for the application
  port: 8000
  # -- URL suffix for the application. The same value should also be included into ingress.path
  docsUrl: /docs
  # -- Config directory for the application
  confDir: /app/conf
  # -- URL of the API Key Manager service (internal)
  uacUrl: http://apikeymanager.processing.svc.cluster.local:8000/auth/check_key
  # -- URL of the API Key Manager home page (public)
  uacHomeUrl: https://apikeymanager.{{ platform_domain_name }}/docs
  # -- Bucket configuration to use to monitor the lifespan and name of data buckets
  # Use an external configuration through an external configmap with the value "externalCatalogBucketConfigMapName"
  # OR
  # Set your own configuration in the value expirationBucketCsv
  bucketConfig:
    # -- Set to true to use an external configmap for the configuration instead of the one set in expirationBucketCsv
    useExternalStagingBucketConfigMap: true
    # -- Name of the external configmap to use. Used only if useExternalCatalogBucketConfigMap is true
    externalStagingBucketConfigMapName: "rs-catalog-staging-configmap"

# -- Pod affinity
affinity:
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: node-role.kubernetes.io/processing
         operator: Exists

# -- Pod toleration
tolerations:
- key: role
  operator: Equal
  value: processing
  effect: NoSchedule

# -- Pod initContainers
initContainers:
- name: init-check
  image: alpine/curl:latest
  command:
    - /bin/sh
    - -c
    - |
      until test "$(curl -XGET --silent grafana-tempo-distributor.logging.svc.cluster.local:3100/ready)" = "ready"; do echo grafana-tempo-distributor is not ready; sleep 2; done; echo grafana-tempo-distributor reached

obs:
  # -- URL of the object storage service endpoint
  endpoint: {{ s3.endpoint }}
  # -- Region of the object storage service
  region: {{ s3.region }}
  secret:
    # -- Access Key to authenticate with the object storage service
    ak: {{ s3.access_key }}
    # -- Secret Key to authenticate with the object storage service
    sk: {{ s3.secret_key }}

auth:
  secret:
    # -- OIDC End Point
    oidc_endpoint: "https://iam.{{ platform_domain_name }}"
    # -- OIDC Realm
    oidc_realm: "rspy"
    # -- OIDC CLient ID
    oidc_client_id: "osam"
    # -- OIDC Secret used to sync user info from Keycloak
    oidc_client_secret: "{{ osam_oidc_client_secret }}"
    # -- Random string used to encode cookie-based HTTP sessions in SessionMiddleware
    cookie_secret: "{{ rsserver_cookieSecret }}"

provider:
  secret:
    # -- OVH End Point
    ovh_endpoint: "{{ rs_osam.provider.secret.ovh_endpoint }}"    
    # -- OVH Application Key
    ovh_application_key: "{{ rs_osam.provider.secret.ovh_application_key }}" 
    # -- OVH Application Secret
    ovh_application_secret: "{{ rs_osam.provider.secret.ovh_application_secret }}" 
    # -- OVH Consumer Key
    ovh_consumer_key: "{{ rs_osam.provider.secret.ovh_consumer_key }}" 
    # OVH Service (used in endpoint /cloud/project/<ovh_service>/user )
    ovh_service: "{{ rs_osam.provider.secret.ovh_service }}" 

ingress:
  # -- Enabled/Disable ingress
  enabled: true
  issuer:
    # -- Ingress Issuer type
    type: cluster-issuer
    # -- Ingress Issuer name
    name: letsencrypt-prod
  # -- Ingress host name
  host: {{ platform_domain_name }}
  # -- Ingress path for the application
  path:
    - /storage