# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# === Worklow behavior ===
#
# On automatic triggers (push or pull):
# - Check for changes in the files related to the Dask images and the base images
# - Build the base images for Dask if there are changes in the base files
# - Set environment for images build
# - Build only the Dask image linked to the detected changes, or all images if there are changes in the common files or if the base images are rebuilt
#   Each image is always built for all three target systems (cluster, local and localcluster)
# - Test rs-demo with the newly built images
#
# On manual trigger:
# - The user chooses which processor to build (cpm2, cpm3, l0, s1ard, s3olci, mockup or all) and for which target system (cluster, local, localcluster or all), and also to rebuild the base images or not
# - Changes are checked like in automatic mode
# - The images built are the ones for the detected changes like in automatic mode AND the ones requested by the user
# - rs-demo tests are run like in automatic mode

name: Build the Dask EOPF/DPR Docker images

# Run workflow only for ...
on:
  pull_request: # pull requests
    types: [opened, synchronize, reopened]
    paths:
      - 'docker/base/**'
      - 'docker/eopf/**'
      - 'docker/scripts/**'
      - '.github/workflows/build-dask-eopf.yml'
  push:
    branches: [develop, main] # pushes on the 'develop' or 'main' branches
    tags: ['**'] # new git tags (including hierarchical tags like v1.0/beta)
    paths:
      - 'docker/base/**'
      - 'docker/eopf/**'
      - 'docker/scripts/**'
      - '.github/workflows/build-dask-eopf.yml'
  workflow_dispatch: # manual trigger
    inputs:
      build_base_images:
        description: Build the base images before building the Dask images?
        type: boolean
        default: true
      processor:
        description: Which processor to build an image for
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - cpm2
          - cpm3
          - l0
          - s1ard
          - s3olci
          - mockup
      target_system:
        description: Whether to build images for cluster deployment, local deployment, LocalCluster mode or all of them
        required: false
        default: 'cluster'
        type: choice
        options:
          - all
          - cluster
          - local
          - localcluster
      add_docker_tags:
        description: Add these tags to the docker images as e.g. 'custom-tag1,custom-tag-2'
        required: false

env:
  DOCKER_REGISTRY: ghcr.io

jobs:

  # Enable conditional execution of workflow steps and jobs, based on the files modified
  # by pull request, on a feature branch, or by the recently pushed commits.
  changes:
    runs-on: ubuntu-latest
    name: Check modified files
    permissions:
      pull-requests: read
    outputs:
      # Note: we tie "base" and "common" outputs to the manual trigger as well,
      # to trigger all the image builds anytime the workflow is triggered manually.
      base: ${{ steps.filter.outputs.base }}
      common: ${{ steps.filter.outputs.common }}
      cpm2: ${{ steps.filter.outputs.cpm2 }}
      cpm3: ${{ steps.filter.outputs.cpm3 }}
      l0: ${{ steps.filter.outputs.l0 }}
      s1ard: ${{ steps.filter.outputs.s1ard }}
      s3olci: ${{ steps.filter.outputs.s3olci }}
      any_changes: ${{ steps.any_changes.outputs.value }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            base:
              - docker/base/build-base-images.sh
              - docker/base/Dockerfile.dask.k8s
              - docker/base/Dockerfile.dask.local
              - docker/scripts/dask-cluster-versions.yml
            common:
              - docker/eopf/build_dask_eopf.py
              - docker/eopf/Dockerfile.dask-eopf
              - docker/eopf/Dockerfile.dask-eopf-localcluster
              - docker/eopf/resources/layer-cleanup.sh
              - docker/eopf/resources/restore-apt.sh
            cpm2: ['docker/**/*dask-cpm.*']
            cpm3: ['docker/**/*dask-cpm.*']
            l0: ['docker/**/*dask-l0.*', 'docker/**/l0/*']
            s1ard: ['docker/**/*dask-s1ard.*']
            s3olci: ['docker/**/*dask-s3olci.*']
          list-files: 'json' # Enables listing of files matching the filter
      - id: any_changes
        name: Any changes ?
        run: |
          set -x
          # Do we have any changes in the processor files ?
          any_changes=false
          if [[ \
            (${{ steps.filter.outputs.base }} == 'true') || \
            (${{ steps.filter.outputs.common }} == 'true') || \
            (${{ steps.filter.outputs.cpm2 }} == 'true') || \
            (${{ steps.filter.outputs.cpm3 }} == 'true') || \
            (${{ steps.filter.outputs.l0 }} == 'true') || \
            (${{ steps.filter.outputs.s1ard }} == 'true') || \
            (${{ steps.filter.outputs.s3olci }} == 'true') \
          ]]; then
            any_changes=true
          fi
          echo "value=$any_changes" >> $GITHUB_OUTPUT
        shell: bash

  set-binary-env:
    name: Set Docker environment
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set-binary-env.outputs.branch_name }}
      docker_tags: ${{ steps.set-binary-env.outputs.docker_tags }}
      docker_final_tags: ${{ steps.set-binary-env.outputs.docker_final_tags }}
      rs_testmeans_branch: ${{ steps.rs-testmeans.outputs.branch }}
    steps:
      - id: set-binary-env
        name: Call action 'set-binary-env'
        uses: RS-PYTHON/actions/.github/actions/set-binary-env@develop
        with:
          add_docker_tags: ${{ inputs.add_docker_tags }}
      - name: Branch name in rs-testmeans
        id: rs-testmeans
        uses: RS-PYTHON/actions/.github/actions/get-repo-branch@develop
        with:
          repo: RS-PYTHON/rs-testmeans
          branches: ${{ steps.set-binary-env.outputs.branch_name }},develop

  build-base-dask-images:
    runs-on: ubuntu-latest
    name: Build base images for Dask
    needs: [changes]
    if: ${{
      ((github.event_name != 'workflow_dispatch') && (needs.changes.outputs.base == 'true')) ||
      ((github.event_name == 'workflow_dispatch') && (inputs.build_base_images == true))
      }}
    permissions:
      packages: write # needed for 'docker push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username "${{ github.actor }}" --password-stdin
      - name: Build and push base images
        run: docker/base/build-base-images.sh -t dask --push

  trigger-rs-testmeans:
    runs-on: ubuntu-latest
    name: Trigger rs-testmeans # to build the Dask mockup image for local mode from the Dask base image
    needs: [set-binary-env, build-base-dask-images]
    permissions:
      packages: write # needed for 'docker push'
    steps:
      # When we merge to develop, rs-testmeans will first use a temp docker tag, then run the tests,
      # then retag the images with the final tag.
      # If two workflow runs do it in parallel, we can have conflicts: a temp tag with errors
      # could be retagged as final and pushed.
      # In this case, we cancel the existings runs before triggering a new run with the new base image.
      - name: Cancel existing runs
        if: ${{ needs.set-binary-env.outputs.docker_final_tags != '' }}
        uses: RS-PYTHON/actions/.github/actions/cancel-workflow-runs@develop
        with:
          trigger_workflows_token: ${{ secrets.TRIGGER_WORKFLOWS }}
          owner_repo: RS-PYTHON/rs-testmeans
          workflow_path: .github/workflows/publish-binaries.yml
          branch: ${{ needs.set-binary-env.outputs.rs_testmeans_branch }}
      - name: Trigger a new run
        # Link to the URL of this current github actions run
        env:
          THIS_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        uses: benc-uk/workflow-dispatch@ba9b031f598534deb29873396ef7b0acf17aa94a
        with:
          workflow: publish-binaries.yml
          repo: RS-PYTHON/rs-testmeans
          ref: ${{ needs.set-binary-env.outputs.rs_testmeans_branch }}
          # Use the same docker tags as in the current workflow run, even if we
          # are in a branch and rs-testmeans is on develop.
          inputs: '{
            "called_by": "rebuild-base-dask",
            "force_docker_tags": "${{ needs.set-binary-env.outputs.docker_tags }}",
            "force_docker_final_tags": "${{ needs.set-binary-env.outputs.docker_final_tags }}",
            "caller_name": "rs-workflow-env",
            "caller_url": "${{ env.THIS_URL }}",
            "caller_reason": "Build the Dask mockup image for local mode from the Dask base image."
            }'
          token: '${{ secrets.TRIGGER_WORKFLOWS }}'
          wait-for-completion: true
          wait-timeout-seconds: 3600
          sync-status: true

  build-dask-eopf:
    runs-on: ubuntu-latest
    name: Build images for processor
    needs: [changes, set-binary-env, build-base-dask-images]
    # Job run when there are changes OR a manual trigger, EVEN if any previous job is skipped
    if: ${{
      always() && !failure() && !cancelled() &&
      ((needs.changes.outputs.any_changes == 'true') || (github.event_name == 'workflow_dispatch'))
      }}
    permissions:
      security-events: write # needed for github/codeql-action/upload-sarif
      packages: write # needed for 'docker push'
    env:
      # Use directly the final tags
      DOCKER_TAGS: ${{ needs.set-binary-env.outputs.docker_tags }},${{ needs.set-binary-env.outputs.docker_final_tags }}

    # See: https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations
    strategy:
      fail-fast: false
      matrix:
        proc: [cpm2, cpm3, l0, s1ard, s3olci]
        target: [cluster, local, localcluster] # No option = main image for cluster deployment, "local" is for local deployment and "localcluster" is for local debugging
        include:
          - proc: cpm2
            proccondition: ${{
              ((github.event_name != 'workflow_dispatch') && (
                (needs.changes.outputs.cpm2 == 'true') ||
                (needs.changes.outputs.common == 'true') ||
                (needs.changes.outputs.base == 'true')
              )) ||
              ((github.event_name == 'workflow_dispatch') && (
                (inputs.processor == 'cpm2') ||
                (inputs.processor == 'all')
              ))}}
          - proc: cpm3
            proccondition: ${{
              ((github.event_name != 'workflow_dispatch') && (
                (needs.changes.outputs.cpm3 == 'true') ||
                (needs.changes.outputs.common == 'true') ||
                (needs.changes.outputs.base == 'true')
              )) ||
              ((github.event_name == 'workflow_dispatch') && (
                (inputs.processor == 'cpm3') ||
                (inputs.processor == 'all')
              ))}}
          - proc: l0
            proccondition: ${{
              ((github.event_name != 'workflow_dispatch') && (
                (needs.changes.outputs.l0 == 'true') ||
                (needs.changes.outputs.common == 'true') ||
                (needs.changes.outputs.base == 'true')
              )) ||
              ((github.event_name == 'workflow_dispatch') && (
                (inputs.processor == 'l0') ||
                (inputs.processor == 'all')
              ))}}
          - proc: s1ard
            proccondition: ${{
              ((github.event_name != 'workflow_dispatch') && (
                (needs.changes.outputs.s1ard == 'true') ||
                (needs.changes.outputs.common == 'true') ||
                (needs.changes.outputs.base == 'true')
              )) ||
              ((github.event_name == 'workflow_dispatch') && (
                (inputs.processor == 's1ard') ||
                (inputs.processor == 'all')
              ))}}
          - proc: s3olci
            proccondition: ${{
              ((github.event_name != 'workflow_dispatch') && (
                (needs.changes.outputs.s3olci == 'true') ||
                (needs.changes.outputs.common == 'true') ||
                (needs.changes.outputs.base == 'true')
              )) ||
              ((github.event_name == 'workflow_dispatch') && (
                (inputs.processor == 's3olci') ||
                (inputs.processor == 'all')
              ))}}
          - target: cluster
            targetcondition: ${{
              (github.event_name != 'workflow_dispatch') ||
              (inputs.target_system == 'cluster') ||
              (inputs.target_system == 'all')}}
          - target: local
            targetcondition: ${{
              (github.event_name != 'workflow_dispatch') ||
              (inputs.target_system == 'local') ||
              (inputs.target_system == 'all')}}
          - target: localcluster
            targetcondition: ${{
              (github.event_name != 'workflow_dispatch') ||
              (inputs.target_system == 'localcluster') ||
              (inputs.target_system == 'all')}}

    steps:
      - name: Display build info
        run: |
          echo "Building image for processor ${{ matrix.proc }} and target ${{ matrix.target }}"
          echo "Processor condition: ${{ matrix.proccondition }}"
          echo "Target condition: ${{ matrix.targetcondition }}"
        shell: bash

      - name: Checkout
        if: ${{ matrix.proccondition && matrix.targetcondition }}
        uses: actions/checkout@v6

      # Login to Docker Hub to increase pull quota from 100 to 200 per 6 hours
      - name: Log into Docker Hub
        if: ${{ matrix.proccondition && matrix.targetcondition }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log into GitHub Container Registry
        if: ${{ matrix.proccondition && matrix.targetcondition }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata from Git reference and GitHub events
      - name: Extract Docker metadata
        id: meta
        if: ${{ matrix.proccondition && matrix.targetcondition }}
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }} # ghcr.io/RS-PYTHON/rs-workflow-env

      - id: build
        name: Build the Dask images
        if: ${{ matrix.proccondition && matrix.targetcondition }}
        run: |
          set -x

          if [[ "${{ matrix.target }}" == "localcluster" ]]; then
            options="--local_cluster"
          fi

          if [[ "${{ matrix.target }}" == "local" ]]; then
            options="--local"
          fi

          ./docker/eopf/build_dask_eopf.py \
            --gitlab_eopf_token "${{ secrets.GITLAB_EOPF_TOKEN }}" \
            --docker_tags $DOCKER_TAGS \
            --labels "${{ steps.meta.outputs.labels }}" \
            $options \
            ${{ matrix.proc }}

          # Get the docker image name and tag that was built
          last_built=$(docker images | awk 'NR==2')
          repository=$(echo "$last_built" | awk '{print $1}')
          repository_and_tag=$(echo "$last_built" | awk '{print $1 ":" $2}')

          # Save values
          echo "repository=$repository" >> $GITHUB_OUTPUT
          echo "repository_and_tag=$repository_and_tag" >> $GITHUB_OUTPUT
        shell: bash

      - name: Run Trivy vulnerability scanner
        if: ${{ matrix.proccondition && matrix.targetcondition }}
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          version: v0.69.3
          image-ref: ${{ steps.build.outputs.repository_and_tag }}
          format: sarif
          output: trivy-results-docker.sarif
          exit-code: 0
          limit-severities-for-sarif: true
          severity: HIGH,CRITICAL
          #timeout: '30m'

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ matrix.proccondition && matrix.targetcondition }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-results-docker.sarif
          category: ${{ steps.build.outputs.repository }}

      - name: Display link to Trivy results
        if: ${{ matrix.proccondition && matrix.targetcondition }}
        run: |
            set -x

            # If this is not a pull request, the query is "is:open+branch:branch_name"
            if [[ "${{ github.ref_name }}" != *merge* ]]; then
              query="is:open+branch:${{ github.ref_name }}"

            # Else the ref_name is e.g. '13/merge'. Change it into 'pr:13'
            else
              query=$(sed "s|\(.*\)/merge|pr:\1|g" <<< "${{ github.ref_name }}")
            fi

            echo "Trivy scan results:" \
            "https://github.com/${{ github.repository }}/security/code-scanning?query=${query}" \
            >> $GITHUB_STEP_SUMMARY
        shell: bash

      - name: Push Docker image
        if: ${{ matrix.proccondition && matrix.targetcondition }}
        run: |
          set -x
          for tag in ${DOCKER_TAGS//,/ }; do
            docker push ${{ steps.build.outputs.repository }}:${tag}
          done
        shell: bash
