# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# === Worklow behavior ===
#
# On automatic triggers (push or pull):
# - Check for changes in the files related the base images
# - Build the base images for Dask if there are changes in the base files
# - Set environment for images build
# - Build the Jupyter image
#
# On manual trigger: same workflow but the user can choose to build the base image or not.
# However, if changes are detected in the base images files, it will be built whatever the user choice

name: Build the Jupyter Docker image

# Run workflow only for ...
on:
  pull_request: # pull requests
    types: [opened, synchronize, reopened]
    branches: none
    paths:
      - 'docker/base/**'
      - 'docker/jupyter/**'
      - 'docker/scripts/**'
      - '.github/workflows/build-jupyter.yml'
  push:
    branches: [develop, main] # pushes on the 'develop' or 'main' branches
    tags: ['**'] # new git tags (including hierarchical tags like v1.0/beta)
    paths:
      - 'docker/base/**'
      - 'docker/jupyter/**'
      - 'docker/scripts/**'
      - '.github/workflows/build-jupyter.yml'
  workflow_dispatch: # manual trigger
    inputs:
      add_docker_tags:
        description: Add these tags to the docker images as e.g. 'custom-tag1,custom-tag-2'
        required: false
      build_base_image:
        description: Build the base image before building the Jupyter image?
        type: boolean
        default: true

env:
  DOCKER_REGISTRY: ghcr.io
  TRIVY_SKIP_DIRS: /opt/conda/pkgs/cache
  TRIVY_SKIP_FILES: /opt/conda/lib/python3.*/site-packages/bokeh/server/static/js/compiler.js,/opt/conda/lib/python3.*/site-packages/prefect/server/ui/assets/index-CCNfsmcm.js.map

jobs:
  # Enable conditional execution of workflow steps and jobs, based on the files modified
  # by pull request, on a feature branch, or by the recently pushed commits.
  changes:
    runs-on: ubuntu-latest
    name: Check modified files for base images
    permissions:
      pull-requests: read
    outputs:
      base: ${{ steps.filter.outputs.base }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            base:
              - docker/base/Dockerfile.jupyter
              - docker/scripts/create-jupyter-kernels.sh
              - docker/scripts/dask-cluster-versions.yml
          list-files: 'json' # Enables listing of files matching the filter
  set-binary-env:
    name: Set Docker environment
    if: github.actor != 'dependabot[bot]' # ignore pull requests by github bot
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set-binary-env.outputs.branch_name }}
      docker_tags: ${{ steps.set-binary-env.outputs.docker_tags }}
      docker_final_tags: ${{ steps.set-binary-env.outputs.docker_final_tags }}
      base_jupyter_tag: ${{ steps.base-jupyter-tag.outputs.value }}
      rs_client_branch: ${{ steps.rs-client-libraries.outputs.branch }}
    steps:
      - id: set-binary-env
        name: Call action 'set-binary-env'
        uses: RS-PYTHON/actions/.github/actions/set-binary-env@feat-rspy1108/jupyter-cicd
        with:
          add_docker_tags: ${{ inputs.add_docker_tags }}
      - name: Tag of the base Jupyter Docker image
        id: base-jupyter-tag
        run: |
          set -x
          # Keep last tag (after the last ',')
          docker_tags=${{ steps.set-binary-env.outputs.docker_tags }}
          value=${docker_tags##*,}
          echo "value=$value" >> $GITHUB_OUTPUT
      - name: Branch name in rs-client-libraries
        id: rs-client-libraries
        uses: RS-PYTHON/actions/.github/actions/get-repo-branch@feat-rspy1108/jupyter-cicd
        with:
          repo: RS-PYTHON/rs-client-libraries
          branches: ${{ steps.set-binary-env.outputs.branch_name }},develop

  build-base-jupyter-image:
    runs-on: ubuntu-latest
    name: Build base image for Jupyter
    needs: [set-binary-env, changes]
    if: ${{
      ((github.event_name != 'workflow_dispatch') && (needs.changes.outputs.base == 'true')) ||
      ((github.event_name == 'workflow_dispatch') && (inputs.build_base_image == true))
      }}
    permissions:
      security-events: write # needed for github/codeql-action/upload-sarif
      packages: write # needed for 'docker push'
    outputs:
      docker_images: ${{ steps.publish-docker.outputs.docker_images }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - id: publish-docker
        uses: RS-PYTHON/actions/.github/actions/publish-docker@feat-rspy1108/jupyter-cicd
        with:
          dockerfile: ./docker/base/Dockerfile.jupyter
          build_context_path: ./docker/scripts
          image_basename: ${{ github.repository_owner }}/
          image_suffix: quay.io/jupyter/base-notebook
          image_tags: ${{ needs.set-binary-env.outputs.docker_tags }}
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trivy_skip_dirs: ${{ env.TRIVY_SKIP_DIRS }}
          trivy_skip_files: ${{ env.TRIVY_SKIP_FILES }}

  trigger-rs-client-libraries:
    runs-on: ubuntu-latest
    name: Trigger rs-client-libraries # to build the jupyter image for local mode from the base image
    needs: [set-binary-env, build-base-jupyter-image]
    permissions:
      packages: write # needed for 'docker push'
    steps:
      # When we merge to develop, rs-client will first use a temp docker tag, then run the tests,
      # then retag the images with the final tag.
      # If two workflow runs do it in parallel, we can have conflicts.
      # In this case, we cancel the existings runs before triggering a new run with the new base image.
      - name: Cancel existing runs
        if: ${{ needs.set-binary-env.outputs.docker_final_tags != '' }}
        uses: RS-PYTHON/actions/.github/actions/cancel-workflow-runs@feat-rspy1108/jupyter-cicd
        with:
          trigger_workflows_token: ${{ secrets.TRIGGER_WORKFLOWS }}
          owner_repo: RS-PYTHON/rs-client-libraries
          workflow_path: .github/workflows/publish-binaries.yml
          branch: ${{ needs.set-binary-env.outputs.rs_client_branch }}
      - name: Trigger a new run
        uses: benc-uk/workflow-dispatch@7a027648b88c2413826b6ddd6c76114894dc5ec4
        with:
          workflow: publish-binaries.yml
          repo: RS-PYTHON/rs-client-libraries
          ref: ${{ needs.set-binary-env.outputs.rs_client_branch }}
          # Use the same docker tags as in the current workflow run, even if we
          # are in a branch and rs-client-libraries is on develop.
          inputs: '{
            "called_by": "rebuild-base-jupyter",
            "base_jupyter_tag": "${{ needs.set-binary-env.outputs.base_jupyter_tag }}",
            "force_docker_tags": "${{ needs.set-binary-env.outputs.docker_tags }}",
            "force_docker_final_tags": "${{ needs.set-binary-env.outputs.docker_final_tags }}"
            }'
          token: '${{ secrets.TRIGGER_WORKFLOWS }}'
          wait-for-completion: true
          wait-timeout-seconds: 3600

      # If we used a temp docker tag, and only if the rs-client tests succeeded, then
      # we tag the base jupyter image with the real tags and push them.
      - name: Tag and push Docker images
        if: ${{ needs.set-binary-env.outputs.docker_final_tags != '' }}
        uses: RS-PYTHON/actions/.github/actions/tag-push-docker@feat-rspy1108/jupyter-cicd
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          old_docker_images: ${{ needs.build-base-jupyter-image.outputs.docker_images }}
          new_tags: ${{ needs.set-binary-env.outputs.docker_final_tags }}

  build-rs-client-wheel:
    name: Build rs-client-libraries wheel
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' # ignore pull requests by github bot
    needs: [set-binary-env]
    steps:
      - uses: actions/checkout@v6
        with:
          repository: RS-PYTHON/rs-client-libraries

          ref: ${{ needs.set-binary-env.outputs.rs_client_branch }}
          fetch-depth: 0 # so that Dunamai produce the correct version
      - id: build-wheel
        uses: RS-PYTHON/actions/.github/actions/build-wheel@develop

  publish-docker:
    if: ${{ always() && !failure() && !cancelled() && (github.actor != 'dependabot[bot]') }} # Run the job even if previous job was skipped
    runs-on: ubuntu-latest
    name: Build image for Jupyter
    needs: [set-binary-env, build-base-jupyter-image, build-rs-client-wheel]
    permissions:
      security-events: write # needed for github/codeql-action/upload-sarif
      packages: write # needed for 'docker push'
    steps:
      - uses: actions/checkout@v6
      - name: Copy common requirements
        id: copy_common_req
        shell: bash
        run: |
          mkdir -p ./docker/jupyter/resources/
          cp ./docker/scripts/*.* ./docker/jupyter/resources/

      - name: Download .whl dependency
        uses: actions/download-artifact@v8
        with:
          pattern: rs_client_libraries-*.whl
          path: ./docker/jupyter

      - name: Resolve rs-demo branch
        id: rs-demo-branch
        uses: RS-PYTHON/actions/.github/actions/get-repo-branch@feat-rspy1108/jupyter-cicd
        with:
          repo: RS-PYTHON/rs-demo
          branches: ${{ needs.set-binary-env.outputs.branch_name }},develop

      - id: publish-docker
        uses: RS-PYTHON/actions/.github/actions/publish-docker@feat-rspy1108/jupyter-cicd
        with:
          dockerfile: ./docker/jupyter/Dockerfile
          build_context_path: ./docker/jupyter
          image_suffix: -jupyter
          image_tags: ${{ needs.set-binary-env.outputs.docker_tags }}
          build_args: |
            BASE_TAG=${{ needs.set-binary-env.outputs.base_jupyter_tag }}
            CACHEBUST=${{ github.run_id }}
            RS_DEMO_BRANCH=${{ steps.rs-demo-branch.outputs.branch }}
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trivy_skip_dirs: ${{ env.TRIVY_SKIP_DIRS }}
          trivy_skip_files: ${{ env.TRIVY_SKIP_FILES }}

      # If we used a temp docker tag, we tag the jupyter image with the real tags and push them.
      - name: Tag and push Docker images
        if: ${{ needs.set-binary-env.outputs.docker_final_tags != '' }}
        uses: RS-PYTHON/actions/.github/actions/tag-push-docker@feat-rspy1108/jupyter-cicd
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          old_docker_images: ${{ steps.publish-docker.outputs.docker_images }}
          new_tags: ${{ needs.set-binary-env.outputs.docker_final_tags }}
