# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# === Worklow behavior ===
#
# On automatic triggers (push or pull):
# - Check for changes in the files related the base images
# - Build the base images for Dask if there are changes in the base files
# - Set environment for images build
# - Build the Jupyter image
#
# On manual trigger: same workflow but the user can choose to build the base image or not.
# However, if changes are detected in the base images files, it will be built whatever the user choice

name: Build the Jupyter Docker image

# Run workflow only for ...
on:
  pull_request: # pull requests
    types: [opened, synchronize, reopened]
    paths:
      - 'docker/base/**'
      - 'docker/jupyter/**'
      - 'docker/scripts/**'
      - '.github/workflows/build-jupyter.yml'
  push:
    branches: [develop, main] # pushes on the 'develop' or 'main' branches
    tags: ['**'] # new git tags (including hierarchical tags like v1.0/beta)
    paths:
      - 'docker/base/**'
      - 'docker/jupyter/**'
      - 'docker/scripts/**'
      - '.github/workflows/build-jupyter.yml'
  workflow_dispatch: # manual trigger
    inputs:
      docker_tag:
        description: Tag the docker images as e.g. 'latest'
        required: false
      build_base_image:
        description: Build the base image before building the Jupyter image?
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

env:
  DOCKER_REGISTRY: ghcr.io

jobs:

  # Enable conditional execution of workflow steps and jobs, based on the files modified
  # by pull request, on a feature branch, or by the recently pushed commits.
  changes:
    runs-on: ubuntu-latest
    name: Check modified files for base images
    permissions:
      pull-requests: read
    outputs:
      base: ${{ steps.filter.outputs.base }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            base:
              - docker/base/build-base-images.sh
              - docker/base/Dockerfile.jupyter
              - docker/base/Dockerfile.python
          list-files: 'json' # Enables listing of files matching the filter

  # Build base image for Jupyter only
  build-base-jupyter-image:
    runs-on: ubuntu-latest
    name: Build base image for Jupyter
    needs: [changes]
    if: ${{ (needs.changes.outputs.base == 'true') || ((github.event_name == 'workflow_dispatch') && (github.event.inputs.build_base_image == 'true')) }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io --username "${{ github.actor }}" --password-stdin
      - name: Build and push base image
        run: docker/base/build-base-images.sh -t jupyter --push

  set-env:
    name: Set environment
    if: github.actor != 'dependabot[bot]' # ignore pull requests by github bot
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set-binary-env.outputs.branch_name }}
      docker_tags: ${{ steps.set-binary-env.outputs.docker_tags }}
    steps:
      - id: set-binary-env
        name: Call action 'set-binary-env'
        uses: RS-PYTHON/actions/.github/actions/set-binary-env@feat-rspy964/push-latest-after-tests
        with:
          manual_tag: ${{ github.event.inputs.docker_tag }}

  publish-docker:
    if: ${{ always() && !failure() && !cancelled() && (github.actor != 'dependabot[bot]') }} # Run the job even if previous job was skipped
    runs-on: ubuntu-latest
    name: Build image for Jupyter
    needs: [set-env, build-base-jupyter-image]
    permissions: write-all
    steps:
      - uses: actions/checkout@v6

      - name: Copy common requirements
        id: copy_common_req
        shell: bash
        run: |
          mkdir -p ./docker/jupyter/resources/
          cp ./docker/scripts/*.* ./docker/jupyter/resources/

      - id: rs-client-run-id
        name: Get latest run ID from rs-client-libraries
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: rs-client-libraries
          RS_SERVER_PAT: ${{ secrets.RS_SERVER_PAT }}
          WORKFLOW_FILE: "publish-binaries.yml"
          CURRENT_BRANCH: ${{ needs.set-env.outputs.branch_name }}
        run: |
          set -x

          # Test to download from the current branch name, or develop
          if [[ $CURRENT_BRANCH == develop ]]; then
              BRANCHES="develop"
          else
              BRANCHES="$CURRENT_BRANCH develop"
          fi
          for BRANCH in $BRANCHES; do

              # Fetch the latest run for the branch
              URL="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_FILE/runs?branch=$BRANCH&status=completed&per_page=1"
              echo "$URL"
              RUNS=$(curl -s -H "Authorization: Bearer $RS_SERVER_PAT" "$URL")

              # Extract the run ID
              RUN_ID=$(echo "$RUNS" | jq -r '.workflow_runs[0].id')
              if [[ -z "$RUN_ID" || "$RUN_ID" == null ]]; then
                  echo "No workflow run found for branch $BRANCH in $REPO_OWNER/$REPO_NAME"
              else
                  echo "Latest run ID from $BRANCH: $RUN_ID"
                  echo "run-id=$RUN_ID" >> $GITHUB_OUTPUT
                  exit 0
              fi
          done

          # No branch found
          exit 1

      - name: Download rs-client-libraries-wheels
        uses: actions/download-artifact@v4
        with:
          path: ./docker/jupyter
          pattern: rs_client_libraries-*-py3-none-any.whl
          merge-multiple: true
          github-token: ${{ secrets.RS_SERVER_PAT }}
          repository: RS-PYTHON/rs-client-libraries
          run-id: ${{ steps.rs-client-run-id.outputs.run-id }}

      - id: publish-docker
        uses: RS-PYTHON/actions/.github/actions/publish-docker@feat-rspy964/push-latest-after-tests
        with:
          dockerfile: ./docker/jupyter/Dockerfile
          build_context_path: ./docker/jupyter
          image_suffix: -jupyter
          image_tags: ${{ needs.set-env.outputs.docker_tags }}
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build-args: "IMAGE2BUILD=jupyter"
          secrets: "GITLAB_EOPF_TOKEN=${{ secrets.GITLAB_EOPF_TOKEN }}"
          trivy-skip-dirs: /opt/conda/pkgs/cache
          trivy-skip-files: /opt/conda/lib/python3.*/site-packages/bokeh/server/static/js/compiler.js,/opt/conda/lib/python3.*/site-packages/prefect/server/ui/assets/index-CCNfsmcm.js.map
