# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test Ansible playbook deployment

# Run workflow only for ...
on:
  pull_request: # pull requests
    types: [opened, synchronize, reopened]
  push:
    branches: [develop, main] # pushes on the 'develop' or 'main' branches
    tags: ['**'] # new git tags (including hierarchical tags like v1.0/beta)
  workflow_dispatch: # manual trigger
    inputs:
      infra_core_ref:
        description: rs-infra-core branch or tag
        required: true
        default: 'develop'

jobs:
  test-deploy:
    if: github.actor != 'dependabot[bot]' # ignore pull requests by github bot
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Deployment with monitoring"
            deploy_monitoring: true
# TODO enable this in RSPY-836
#          - name: "Deployment without monitoring"
#            deploy_monitoring: false
    name: ${{ matrix.name }}
    steps:
      - name: Check if branch exists in rs-infra-core
        id: check_branch
        env:
          LOCAL_BRANCH: ${{ github.head_ref }}
          INFRA_CORE_REF: ${{ inputs.infra_core_ref || '' }}
        run: |
          BRANCH="${INFRA_CORE_REF:-$LOCAL_BRANCH}"
          if git ls-remote --heads https://github.com/RS-PYTHON/rs-infra-core.git $BRANCH | grep -q $BRANCH; then
            echo "branch_to_use=$BRANCH" >> $GITHUB_OUTPUT
          else
            echo "branch_to_use=" >> $GITHUB_OUTPUT  # Leave empty to use default
          fi
      - name: Checkout infra-core repository
        uses: actions/checkout@v6
        with:
          repository: RS-PYTHON/rs-infra-core
          ref: ${{ steps.check_branch.outputs.branch_to_use }}
      - name: Checkout infra-monitoring repository
        uses: actions/checkout@v6
        if: ${{ matrix.deploy_monitoring }}
        with:
          path: rs-infra-monitoring
          repository: RS-PYTHON/rs-infra-monitoring
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          path: rs-workflow-env
          ref: ${{ github.ref }}
      - name: Aggressive cleanup
        run: |
          # Cleanup disk space (level between 0 and 14, more cleaning takes more time)
          .github/common/resources/aggressive-cleanup.sh 6
      - name: Install requirements
        run: .github/common/resources/install-requirements.sh
      - name: Start minikube
        uses: medyagh/setup-minikube@latest
        with:
          addons: 'metallb,metrics-server'
          cpus: 4
          memory: 8000m
          container-runtime: containerd
          start-args: '--disk-size=32g'
      - name: "Configure cluster labels, IP and DNS (host + CoreDNS)"
        run: |
          if [ "${{ matrix.deploy_monitoring }}" = "true" ]; then
            SUBDOMAINS="dash-dask iam kube monitoring oauth2-proxy processing"
          else
            SUBDOMAINS="dash-dask iam kube oauth2-proxy processing"
          fi
          .github/common/resources/configure-cluster.sh \
            "node-role.kubernetes.io/infra= node-role.kubernetes.io/rs_env= node-role.kubernetes.io/prefect_flow= node-role.kubernetes.io/access_csc=" \
            "$SUBDOMAINS"
      - name: Deploy seaweedfs
        run: |
          if [ "${{ matrix.deploy_monitoring }}" = "true" ]; then
            MINIO_BUCKETS="rs-cluster-psql,rs-cluster-velero,rs-cluster-loki-chunks,rs-cluster-loki-ruler,rs-cluster-tempo"
          else
            MINIO_BUCKETS="rs-cluster-psql,rs-cluster-velero"
          fi
          .github/common/resources/deploy-seaweedfs.sh $MINIO_BUCKETS
      - name: Generate inventory
        run: |
          .github/common/resources/configure-inventory.sh
          # --- Generate inventory
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook registry.yaml -i inventory/mycluster/hosts.yaml -e ci_mode=true
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook generate_inventory.yaml -i inventory/mycluster/hosts.yaml
      - name: Delete specific apps
        run: |
          .github/common/resources/remove-apps.sh
      - name: Deploy the core apps (for real)
        run: |
          # --- Use local cluster issuer instead of Let's Encrypt
          if [ "${{ matrix.deploy_monitoring }}" = "true" ]; then
            .github/common/resources/configure-local-ca.sh \
              dash-dask:dask-gateway iam:iam kube:default monitoring:monitoring processing:processing oauth2-proxy:iam
          else
            .github/common/resources/configure-local-ca.sh \
              dash-dask:dask-gateway iam:iam kube:default processing:processing oauth2-proxy:iam
          fi
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook apps.yaml -i inventory/mycluster/hosts.yaml
      - name: Deploy the monitoring apps (for real)
        if: ${{ matrix.deploy_monitoring }}
        run: |
          ./rs-infra-monitoring/.github/common/resources/configure-minikube-deployment.sh
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook apps.yaml -i inventory/mycluster/hosts.yaml -e '{"package_paths": ["./rs-infra-monitoring/apps/"]}'
      - name: Deploy the workflow-env apps (check)
        run: |
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook --check apps.yaml -i inventory/mycluster/hosts.yaml -e '{"package_paths": ["./rs-workflow-env/apps/"]}' -e private_registry=true
      - name: Deploy the workflow-env apps (for real)
        run: |
          sed -i 's!debug: false!debug: true!g' roles/app-installer/defaults/main.yaml
          sed -i 's!\(ghcr.io/rs-python/rs-workflow-env-jupyter\):[^[:space:]]*!\1:latest!' ./rs-workflow-env/apps/jupyterhub/values.yaml
          ./rs-workflow-env/.github/common/resources/configure-minikube-deployment.sh
          conda run -n rspy --no-capture-output env PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=1 ansible-playbook apps.yaml -i inventory/mycluster/hosts.yaml -e '{"package_paths": ["./rs-workflow-env/apps/"]}'
      - name: 🩺 Kubernetes failure diagnostics
        if: failure()
        run: .github/common/resources/minikube-diagnostics.sh
